name: Auto-Zip and Commit

on:
  push:
    branches:
      - main

jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use the token with write access

      - name: Create ZIP files
        run: |
          mkdir -p scripts/destiny/dist

          # Zip each script file individually
          zip -j scripts/destiny/dist/destiny-windows-powershell.zip scripts/destiny/destiny-windows-powershell.ps1
          zip -j scripts/destiny/dist/destiny-windows-cmd.zip scripts/destiny/destiny-windows-cmd.cmd
          zip -j scripts/destiny/dist/destiny-linux-bash.zip scripts/destiny/destiny-linux-bash.sh
          zip -j scripts/destiny/dist/destiny-mac-bash.zip scripts/destiny/destiny-mac-bash.sh

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push ZIP files
        run: |
          git add scripts/destiny/dist/*.zip
          git commit -m "Auto-generated ZIP files for all destiny scripts" || exit 0
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
